###References https://github.com/hashicorp/setup-terraform
### https://catalog.us-east-1.prod.workshops.aws/workshops/41c5a1b6-bd3e-41f4-bd46-85ab7dc6dad4/en-US/2-fundamentals
name: Terraform VPC Deployment

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write  # Allow GitHub Actions to issue OIDC tokens
  contents: read   # Allows accessing repository content      

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials from OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::098789448788:role/GitHubActionsOIDCRole

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: List directories
      run: ls      

    - name: Change directory to Terraform folder
      run: cd aws

    - name: Terraform Init
      run: terraform init

    # - name: Terraform Plan
    #   run: terraform plan

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
    # 
    # - name: Terraform Output
    #   run: terraform output
